#!/bin/bash

edbc_path0=$(dirname "$0")
edbc_path="$edbc_path0/.."
current_path=$(pwd)

if [ $# -lt 1 ] || [ $# -gt 2 ] 
then 
	echo -e "Usage:\n\tedbc_erlc FILE [OUTPUT_DIR]"
else
	if [ "${1:0:1}" = "/" ]
	then
		file_path=$1
	else
		file_path="$current_path/$1"
	fi
	if [ $# -eq 2 ]
	then
		if [ "${DIR:0:1}" = "/" ]
		then
			ebin_path=$1
		else
			ebin_path="$current_path/$1"
		fi
		erlc -pa "$edbc_path/ebin" -pa "$edbc_path/deps/sheriff/ebin" -pa "$edbc_path/deps/parse_trans/ebin" -I "$edbc_path/include" -o $ebin_path -Dedbc $file_path
	else
		erlc -pa "$edbc_path/ebin" -pa "$edbc_path/deps/sheriff/ebin" -pa "$edbc_path/deps/parse_trans/ebin" -I "$edbc_path/include" -Dedbc $file_path
	fi
fi
